# Generated by Django 5.2.3 on 2026-01-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=600)),
                ('ctf_type', models.CharField(choices=[('Jeopardy Style', 'Jeopardy Style'), ('Attack-Defense', 'Attack-Defense'), ('Mixed', 'Mixed'), ('Red Team', 'Red Team')], max_length=50)),
                ('max_participants', models.IntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('registration_start_date', models.DateField(blank=True, null=True)),
                ('registration_start_time', models.TimeField(blank=True, null=True)),
                ('registration_end_date', models.DateField(blank=True, null=True)),
                ('registration_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('access_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
