# Generated by Django 5.2.3 on 2026-03-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_eventrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('upcoming', 'Upcoming'), ('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='upcoming', max_length=20),
        ),
    ]
