# Generated by Django 5.2.3 on 2026-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_event_is_approved_event_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, help_text='Markdown supported rules for the event', null=True),
        ),
    ]
