# Generated by Django 5.2.3 on 2026-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_event_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepting_writeups',
            field=models.BooleanField(default=False),
        ),
    ]
