# Generated by Django 5.2.3 on 2026-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_event_accepting_writeups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_team_mode',
            field=models.BooleanField(default=False, help_text='Enable team-based scoring for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.PositiveIntegerField(default=4, help_text='Max members per team (team mode only)'),
        ),
    ]
