# Generated by Django 5.2.3 on 2026-01-31 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_hint_cost_userhint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='hint_cost',
        ),
        migrations.CreateModel(
            name='ChallengeHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The hint text')),
                ('cost', models.PositiveIntegerField(default=0, help_text='Points deducted to unlock')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='challenges.challenge')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userhint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userhint',
            name='hint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.challengehint'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userhint',
            unique_together={('user', 'hint')},
        ),
        migrations.RemoveField(
            model_name='userhint',
            name='challenge',
        ),
    ]
