# Generated by Django 5.2.3 on 2026-01-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_hint_remove_challenge_hint_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhint',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challengehint'),
        ),
    ]
