# Generated by Django 5.2.3 on 2026-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_userhint_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the challenge instance (if applicable)', null=True),
        ),
    ]
