# Generated by Django 5.2.3 on 2026-02-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_author_alter_challenge_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='flag_format',
            field=models.CharField(blank=True, default='Hack!tUp{...}', help_text='Format of the flag (e.g. Hack!tUp{...})', max_length=100),
        ),
    ]
