# Generated by Django 5.2.3 on 2026-02-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_event_is_paused_event_is_registration_paused_and_more'),
        ('challenges', '0007_challenge_flag_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=False, help_text='When True, all challenges in this wave become visible to participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='administration.event')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='wave',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make challenge always visible regardless of waves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.challengewave'),
        ),
    ]
