# Generated by Django 5.2.3 on 2026-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_announcement_writeup'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=20),
        ),
    ]
